# Generated by Django 3.2.18 on 2023-06-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0085_alter_resourcebase_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False, help_text='Show it to homepage.')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='delft/icon')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HierarchicalKeywordExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False, help_text='Show it to homepage.')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='delft/icon')),
                ('keyword', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.hierarchicalkeyword')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
