# Generated by Django 3.2.18 on 2023-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0002_groupprofileextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_banner', models.ImageField(blank=True, null=True, upload_to='settings/images')),
                ('landing_page_banner_title', models.TextField(default='')),
                ('landing_page_banner_description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'site preferences',
            },
        ),
    ]
