# Generated by Django 3.2.18 on 2023-08-11 05:53

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0003_sitepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='about_page_content',
            field=mdeditor.fields.MDTextField(default=''),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='about_page_title',
            field=models.TextField(default=''),
        ),
    ]
