# Generated by Django 3.2.18 on 2023-08-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_resourcebase_uuid'),
        ('delft', '0004_auto_20230811_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBaseExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False, help_text='Show it to homepage.')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.resourcebase')),
            ],
        ),
    ]
