# Generated by Django 3.2.18 on 2023-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0005_resourcebaseextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchicalkeywordextension',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the output in the landing page. The order is based on the order of number. On landing page, the order is from left to right and top to bottom. If there are outputs that are outputs that has order number, the order for those outputs are using name.'),
        ),
        migrations.AddField(
            model_name='regionextension',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the output in the landing page. The order is based on the order of number. On landing page, the order is from left to right and top to bottom. If there are outputs that are outputs that has order number, the order for those outputs are using name.'),
        ),
        migrations.AddField(
            model_name='resourcebaseextension',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the output in the landing page. The order is based on the order of number. On landing page, the order is from left to right and top to bottom. If there are outputs that are outputs that has order number, the order for those outputs are using name.'),
        ),
    ]
