# Generated by Django 3.2.18 on 2023-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0006_auto_20230919_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchicalkeywordextension',
            name='is_initial',
            field=models.BooleanField(default=False, help_text='This is the keywords that will be used on metadata form.'),
        ),
    ]
