# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.contrib.auth.models import Group, Permission
from django.db import migrations


def run(apps, schema_editor):
    file_manager_group, _ = Group.objects.get_or_create(name='file-manager')
    codenames = [
        'add_file', 'change_file', 'delete_file', 'view_file',
        'add_folder', 'change_folder', 'delete_folder', 'view_folder',
        'can_use_directory_listing'
    ]
    for codename in codenames:
        file_manager_group.permissions.add(
            Permission.objects.get(codename=codename)
        )


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('delft', '0008_hierarchicalkeywordextension_is_initial_data'),
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
