# Generated by Django 3.2.18 on 2024-05-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0008_hierarchicalkeywordextension_is_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='google_analytics_measurement_id',
            field=models.CharField(default='', help_text='Google analytics measurement id', max_length=256),
        ),
    ]
